import {
	type ChatInputCommandInteraction,
	type Client,
	EmbedBuilder,
	MessageFlags,
	SlashCommandBuilder,
} from 'discord.js';
import { logs } from '@/services/logs';
import type { Command } from '@/types';

const roasts = [
	"You're like a cloud: when you disappear, it's a beautiful day.",
	'Your Wi-Fi has more bars than your jokes.',
	"I'd agree with you, but then we'd both be wrong.",
	"You're the reason the gene pool needs a lifeguard.",
	'If I wanted a warm take, I would have asked my microwave.',
	"You're proof that even Ctrl+Z can't fix everything.",
	"You're not lazy, you're just on energy-saving mode permanently.",
	"You're the human version of a software update: unnecessary and always popping up.",
	"You're like a 404: missing in all the right places.",
	"You're the typo in a tweet: small, loud, and hard to ignore.",
	"You're the human equivalent of a loading screen stuck at 99%.",
	'Your personality is like a PDF: everyone can see it, nobody wants to.',
	"You're the reason auto-correct gave up.",
	'Your jokes have an expiration date, and it was last week.',
	"You're like a group project: you show up at the end and take credit.",
	"You're not a morning person, or an afternoon person, or an evening person.",
	"You're the reason the mute button was invented.",
	"You're like a broken keyboard: too many issues and no space.",
	"You're the lag spike in a smooth game.",
	"You're the human version of a captcha: annoying and hard to understand.",
	"You're the soundtrack to a skip button.",
	"You're like a pop-up ad: loud, unwanted, and hard to close.",
	"You're a spoiler in a group chat.",
	"You're the extra page that prints every time.",
	"You're the reason the tutorial skips itself.",
	"You're like a half-charged battery: always low energy.",
	"You're the trailer that shows the whole movie.",
	"You're the human form of 'Are you sure?'.",
	"You're like a bad Wi-Fi password: too long and still wrong.",
	"You're the 'terms and conditions' of conversations.",
	"You're the reason 'Do Not Disturb' exists.",
	"You're the human equivalent of a low-resolution image.",
	"You're the typo in 'success'.",
	"You're the extra click in a checkout flow.",
	"You're the reason the progress bar is lying.",
	"You're like a software beta: not ready for release.",
	"You're the human version of a typo in a tattoo.",
	"You're the last slide of a presentation: nobody cares.",
	"You're the plot twist everyone saw coming.",
	"You're the 'skip intro' button of a person.",
	"You're the human version of a 1-star review.",
	"You're the notification that says 'no new notifications'.",
	"You're like a GPS reroute: always a little late.",
	"You're the background app draining the battery.",
	"You're the human version of a broken link.",
	"You're the spoiler warning after the spoiler.",
	"You're like a test environment: things work, but not well.",
	"You're the 'try again' on a form that was already correct.",
	"You're the pop quiz in a chill class.",
	"You're the demo that never ships.",
	"You're the human equivalent of a clippy tooltip.",
	"You're the extra loud commercial between songs.",
	"You're the tiny rock in the shoe of every conversation.",
	"You're like a misclick: immediate regret.",
	"You're the reason people read the room in silence.",
	"You're the error message with no fix.",
	"You're the human version of a '404 jokes not found'.",
	"You're a reminder notification for something nobody cares about.",
	"You're the auto-play video at 3 AM.",
	"You're the 'skip update' that keeps coming back.",
	"You're the human equivalent of a low signal beep.",
	"You're the draft that should've stayed a draft.",
	"You're the unread terms everyone scrolls past.",
	"You're the human version of 'buffering...'.",
	"You're the 'maybe later' of a person.",
	"You're like a missing semicolon: small, but everything breaks.",
	"You're the error that reproduces only in production.",
	"You're the human version of a 'temporary' fix.",
	"You're the reason 'mute all' was invented.",
	"You're like a push notification from an app I don't use.",
	"You're the human equivalent of an unskippable ad.",
	"You're the 'password incorrect' after you just reset it.",
	"You're the early access game that never leaves early access.",
	"You're the spoiler in the title.",
	"You're the meeting that should've been an email.",
	"You're the extra file in the zip.",
	"You're like a fake loading bar: decorative and useless.",
	"You're the human version of a cached error.",
	"You're the bug that management calls a feature.",
	"You're the 'Are you still there?' prompt.",
	"You're the background noise on a podcast.",
	"You're the user who replies-all to everything.",
	"You're the reason the chat has slow mode.",
	"You're like an expired coupon: disappointing and loud about it.",
	"You're the kind of vibe that needs a software update.",
	"You're the human equivalent of a sideways PDF.",
	"You're the extra semicolon that lints still hate.",
	"You're the warning label of a personality.",
	"You're like a pop quiz at the end of a long day.",
	"You're the human version of a corrupted save file.",
	"You're the dot in a 'loading' animation that never finishes.",
	"You're the screen protector bubble of a person.",
	"You're the test that auto-grades itself wrong.",
	"You're the notification that forgot its own content.",
	"You're the human equivalent of a 'beta' sticker.",
	"You're the 1% battery warning of a conversation.",
	"You're the default ringtone of people.",
	"You're the 'back' button of a personality.",
	"You're the wrong charger that still almost fits.",
	"You're the extra comma in a CSV file.",
	"You're the human version of a weak password.",
	"You're the typo that made it to production.",
	"You're the extra plate in the microwave: spinning, no purpose.",
	"You're the reason people double-check.",
	"You're the human version of a low-effort meme.",
	"You're the pop-up that blocks the close button.",
	"You're the human version of 'unexpected token'.",
	"You're the error log nobody reads.",
	"You're the slow lane in a fast world.",
	"You're the reason people set 'Do Not Disturb' and mean it.",
	"You're like a bad blind date: too much hype, not enough payoff.",
	"You're the kind of chaos that doesn't even come with good stories.",
	"You're a walking reminder that confidence isn't the same as competence.",
	"You're the group chat drama that nobody asked for.",
	"You're the human version of 'fine, whatever.'",
	"You're a red flag dressed up as a good time.",
	"You're the reason people ghost.",
	"You're like a nightclub at closing: messy and disappointing.",
	"You're the plot hole in your own life story.",
	"You're a walking 'no thanks.'",
	"You're the reason the block button gets used.",
	"You're like a hangover with no party attached.",
	"You're the human version of a bad aftertaste.",
	"You're the 'last call' nobody wanted.",
	"You're like a breakup text: short, cold, and overdue.",
	"You're the reason people lie about being busy.",
	"You're the late-night idea that should've stayed a draft.",
	"You're a vibe check that failed on arrival.",
	"You're the reason people say 'I'm good' and mean it.",
	"You're the awkward silence after a bad joke.",
	"You're a warning label with legs.",
	"You're the punchline that never lands.",
	"You're the reason 'read receipts' are a thing.",
	"You're the 'maybe next time' of a person.",
	"You're the human version of a 2 AM regret.",
	"You're the extra shot that ruins the night.",
	"You're a whole parade of bad decisions.",
	"You're the reason people turn off notifications.",
	"You're the 'delete for everyone' that didn't make it in time.",
];

const roastCommand: Command = {
	data: new SlashCommandBuilder()
		.setName('roast')
		.setDescription('Playfully roast a user')
		.addUserOption((option) =>
			option.setName('user').setDescription('User to roast').setRequired(true),
		)
		.setContexts([0, 1, 2])
		.setIntegrationTypes([0, 1]),
	userPermissions: [],
	botPermissions: [],
	category: 'Fun',
	cooldown: 5,
	nsfwMode: true,
	deleted: false,
	testMode: false,
	devOnly: false,

	run: async (_client: Client, interaction: ChatInputCommandInteraction): Promise<void> => {
		try {
			const target = interaction.options.getUser('user', true);
			const roast = roasts[Math.floor(Math.random() * roasts.length)];

			const embed = new EmbedBuilder()
				.setColor('#f97316')
				.setTitle('🔥 Roast')
				.setDescription(`${target} ${roast}`)
				.setFooter({
					text: `Requested by ${interaction.user.username}`,
					iconURL: interaction.user.displayAvatarURL(),
				})
				.setTimestamp();

			await interaction.reply({
				embeds: [embed],
				allowedMentions: { users: [target.id] },
			});
		} catch (error) {
			logs.error('Error in roast command', { tag: 'Roast', context: error });
			await interaction.reply({
				content: 'There was an error while executing this command!',
				flags: MessageFlags.Ephemeral,
			});
		}
	},
};

export default roastCommand;
